name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build & Push to GitHub Package
      uses: opspresso/action-docker@master
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        REGISTRY: "docker.pkg.github.com"
        RESISTRY: "docker.pkg.github.com"
        TAG_NAME: "v0.0.1"
        IMAGE_NAME: "joachimprinzbach/shelf"
        LATEST: "true"